### ISSUE TITLE
SRS Review: Instance Models

### ISSUE THREAD

**Issue by samm82** [LesleyWheat/CAS741_CEWS#10]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related.*

- [x] You need to reference your goals statement: "The goal~s~ **GS1 is** ~are~ solved by...."
- [ ] You are missing the definition of $I(..)$ from your Table of Symbols; this should be a separate model.
   - [ ] I'm not sure what its type is, but function application with multiple variables should be written as "$I(c_i = r, c_j = s)$".
- [ ] Description~~s~~ for ~~many variables are~~ $n$ is not provided.

**Comment by LesleyWheat** [comment]
> You are missing the definition of I(..) from your Table of Symbols; this should be a separate model.
>  I'm not sure what its type is, but function application with multiple variables should be written as "$I(c_i = r, c_j = s)$".

I clearly define $I(...)$ as the indicator function, it is not a model. It can take a statement or variable or set.

> * [ ]  Descriptions for many variables are not provided.

Definitions are provided locally.

**Comment by samm82** [comment]
$I(..)$ seems like it would make sense as a data definition, with a link to an appropriate source, that explicitly states its possible inputs and its outputs. While this may be common knowledge for someone in the field, the SRS should be as self-contained as possible.

Looking at it again, most of the variables are just used as indexes for iterating, so they wouldn't really need a description, but $n$ has no description (also in GD1).

(I'm reopening this issue, but feel free to close it again if you disagree.)
