### ISSUE TITLE
SRS Review: Input Data Constraints

### ISSUE THREAD

**Issue by samm82** [LesleyWheat/CAS741_CEWS#11]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

- [x] Table 1 seems to refer to just the input variables, not the "...input output variables."
- [ ] The description of matrix notation should be moved to the Mathematical Notation section. (If it is covered in the source you referenced--I don't have access to the source--then it should just be removed from this section, but keeping the application-specific information, like " $n$ is the number of examples").
   - [ ] The structure of the matrix notation description is a bit awkward; try rewording it so it flows better.
- [x] It looks like the $=$ is a subscript of $C$ when describing its format.
- [x] It would be a good idea to reference the System Context section when saying "It is the user’s responsibility to ...."
- [ ] Having the constraints $n \in \mathbb{N}$ and $n>0$ seems redundant. You should define $\mathbb{N}$ in the Mathematical Notation section. If it always refers to {1, 2, 3...}, then you should remove the $n>0$ constraint; otherwise, you should define a set that meets this criteria (e.g., the whole numbers) and also define it in the notation section.

**Comment by LesleyWheat** [comment]
> The description of matrix notation should be moved to the Mathematical Notation section. (If it is covered in the source you referenced--I don't have access to the source--then it should just be removed from this section, but keeping the application specific information, like " is the number of examples").

You do have access to the sources, all mcmaster students do.

> You should define  in the Mathematical Notation section. 
Updated Characteristics of Intended Reader.

> Having the constraints  n in N and  n > 0 seems redundant. 
This is for clarity and to prevent confusion because some people put 0 in natural numbers. https://mathworld.wolfram.com/NaturalNumber.html
