### ISSUE TITLE
SRS Review: Requirements

### ISSUE THREAD

**Issue by samm82** [LesleyWheat/CAS741_CEWS#12]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

## Functional Requirements
- [ ] R1 should be "**If** any constraint in 4.2.6 is violated, then..." (note the comma).
- [ ] For consistency, R3 should use "will" instead of "should".
- [ ] R4 seems repetitive and vague. What error should be raised by the program? The same one it encountered? A special catch-all?
## Nonfunctional Requirements
- [ ] Where does the value "0.01" come from in NFR1?
- [ ] What do "readable" and "clear" mean in NFR3? This is ambiguous.
-  ~~Which version of Windows 11 should the software run on? (This could be too nitpicky - let's see what @smiths says. 😅)~~
- [ ] Does the software only need to be run on Windows systems? Could it be required for it to also be able to run on macOS and Linux? If there are reasons that it isn't, these should be documented in the System Constraints section.

**Comment by smiths** [comment]
Thanks for the feedback @samm82.  Very thorough!

As far as specifying the specific version of Windows 11, I don't normally look for that level of detail.  It certainly isn't wrong to include it, but I don't consider it as necessary for most scientific software.  (If there were constraints for specific libraries, or specific hardware, then constraints on the OS would also be a good idea.)

I haven't reviewed the document yet, but I do like the OS to be as general as possible.  It usually isn't that much more work to get scientific software to run on Windows, Linux and Mac OS.

**Comment by LesleyWheat** [comment]
> Where does the value "0.01" come from in NFR1?

This doesn't come from anywhere, I made it up, there is no source.

> Does the software only need to be run on Windows systems? Could it be required for it to also be able to run on macOS and Linux? If there are reasons that it isn't, these should be documented in the System Constraints section.

I'm only including OSs that I will be testing on.

**Comment by samm82** [comment]
By convention, the value "0.01" should be defined as a parameter (e.g., MAX_ABSOLUTE_ERROR) that is given a value in the Values of Auxiliary Constants section.
