### ISSUE TITLE
SRS Review: General Grammar/Formatting Issues

### ISSUE THREAD

**Issue by samm82** [LesleyWheat/CAS741_CEWS#15]
The following is a list of small issues that occurred in sections without any other issues in them.

# TODO
*Any point that requires more discussion should be pulled out to a different issue.*

- [ ] Phrases like "fraction of points on class boundary", "cut edge weight statistic" (both in the introduction), or "intended reader" (in Purpose of Document) shouldn't be capitalized. It should be "CEWS measurement", not "CEWS
Measurement", etc.
- [ ] Make sure to using quotation marks correctly in LaTeX (e.g., ``test").
- [x] Most papers put the "p" in "p-value" in italics; I would personally use LaTeX's math mode to indicate that it is a mathematical symbol.
- [x] "Preform" should be "perform" throughout the section.
- [ ] If your program is named "CEWS System", I think it should have a "the" before it; "**The** CEWS System is intended to solve..." sounds more natural to me.
   - [ ] Regardless of the decision, it should be consisten (see Functional Requirements).
- [x] When used as an adjective, "base-2" has a hyphen ([source](https://computer.howstuffworks.com/bytes1.htm)).
- [x] To be consistent, use "does not" in A6.
- [x] There should be a colon or a period at the end of the sentence in Properties of a Correct Solution.
