### ISSUE TITLE
SRS Review: Table of Symbols

### ISSUE THREAD

**Issue by samm82** [LesleyWheat/CAS741_CEWS#3]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

- [x] The sentence "The choice of symbols was made to be consistent with the heat transfer literature and with existing documentation for solar water heating systems," is borrowed from the template and does not reflect your project.
- [ ] Including the type of the indicator function in the table of symbols would be more informative to the reader.
- [ ] There are many symbols missing (just from GD1 you have $E_{\text{RNG}}, P, i, j, d(a, b), c, V, v_{ij},$ and $n)$.

**Comment by LesleyWheat** [comment]
The type of the indicator function is a function. As per the example ( https://github.com/smiths/capTemplate/blob/main/docs/SRS/SRS.pdf ), locally defined symbols are not present in the table of symbols.

**Comment by samm82** [comment]
"Function" is not a complete type: how many inputs does it take? what types are they? what type is its output?

The example template is not extensive; it is essentially just a sampling of an existing example. For example in our [GamePhysics example](https://jacquescarette.github.io/Drasil/examples/gamephysics/SRS/srs/GamePhysics_SRS.html), $||n||$ is only used in the [impulse GD](https://jacquescarette.github.io/Drasil/examples/gamephysics/SRS/srs/GamePhysics_SRS.html#GD:impulse) but still appears in the [Table of Symbols](https://jacquescarette.github.io/Drasil/examples/gamephysics/SRS/srs/GamePhysics_SRS.html#Table:ToS).
