### ISSUE TITLE
SRS Review: Citations

### ISSUE THREAD

**Issue by samm82** [LesleyWheat/CAS741_CEWS#4]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

- [ ] [To avoid plagarism accusations](https://writing.wisc.edu/handbook/assignments/quotingsources/), consider using a direct quote for the definition of separability in the Introduction and Terminology and Definitions sections.
- [x] There is a space missing between "Ho" and "[5]" in the introduction.
- [x] Putting the citation after "Zighed et al." in the third paragraph of the introduction might be better.

**Comment by LesleyWheat** [comment]
> * [ ]  [To avoid plagarism accusations](https://writing.wisc.edu/handbook/assignments/quotingsources/), consider using a direct quote for the definition of separability in the Introduction and Terminology and Definitions sections.

These are not direct quotations. I rewrote these and they are cited correctly.

**Comment by samm82** [comment]
The source says "Separability is an intrinsic characteristic of a dataset [6] to describe how data points belonging to different classes mix with each other," while your SRS says "One of these aspects is separability, an intrinsic characteristic that describes how the data points from different classes mix together [3]." While this isn't word-for-word plagiarism, it is what [the source I linked to](https://writing.wisc.edu/handbook/assignments/quotingsources/) calls a "patchwork paraphrase" and is still a form of plagiarism. Since your sentence is so similar, it is better to just directly cite it.

**Comment by LesleyWheat** [comment]
That is not a McMaster policy and we are not at the University of Wisconsin. McMaster uses the rule of thumb of 4 words https://www.humanities.mcmaster.ca/~pdsavage/pdfs/referencing_guide.pdf which that sentence does not violate. Therefore it is a paraphrase and thus does not need quotations.
