### ISSUE TITLE
SRS Review: System Context

### ISSUE THREAD

**Issue by samm82** [LesleyWheat/CAS741_CEWS#5]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

- [ ] The name "Pre-processing" suggests that it is a stage of CEWS System and not its own standalone system, but it is listed as a user responsibility. If it is its own system used by the user, consider renaming it; otherwise remove it from the system context diagram.
   - [ ] If "Pre-processing" remains in the system context diagram, it should have its own set of responsibilities (and the relevant user responsibilities should be removed).
- [x] Instead of "Provide the data," you should describe what data the user should provide (e.g., the data matrix, the class matrix).
- [x] The "Resource management..." bullet point should begin with an imperative verb for consistency.
- [x] There should be a comma after "Resource management" under User Responsibilities.
- [x] You should link to the constraints mentioned in the CEWS System Responsibilities section.

**Comment by LesleyWheat** [comment]
> The name "Pre-processing" suggests that it is a stage of CEWS System and not its own standalone system, but it is listed as a user responsibility. If it is its own system used by the user, consider renaming it; otherwise remove it from the system context diagram.

This is only included on @smiths request, pre-processing is not part of the system.
