### ISSUE TITLE
SRS Review: Terminology and Definitions

### ISSUE THREAD

**Issue by samm82** [LesleyWheat/CAS741_CEWS#6]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

- [ ] The list of terms should be sorted alphabetically to aid navigation.
- [ ] "Data point", "Example", and "Samples" should all be separate entries, with the latter two directing to the first (i.e., "See 'Data point'.").
- [ ] Terms should have the same grammatical number as their definition (i.e., "Samples"  is plural while "An indentifiable element..." is singular and vice versa for "Data complexity" and its definition).
- [x] There shouldn't be a space before a colon.
- [x] Terms with multiple words should be capitalized consistently; either both capitalized (e.g., "Class Label") or only the first (e.g., "Data point").
- [ ] Should "classification" be defined as "The **process** of identifying..."?
- [ ] Boolean variables are standard enough that they do not need to be defined in this section.

**Comment by LesleyWheat** [comment]
> Should "classification" be defined as "The process of identifying..."?

No, classification is a **problem**.

> Boolean variables are standard enough that they do not need to be defined in this section.

I would normally agree but considering I was asked to define them during my presentation, I included them.

**Comment by samm82** [comment]
> No, classification is a **problem**.

This may be a pedantic issue, but I think that there are "classification problems", and there is the concept of "classification", which is a process. The literature seems to be unclear about this: [this source](https://emeritus.org/blog/artificial-intelligence-and-machine-learning-classification-in-machine-learning/) defines it as "a supervised machine learning **process** of categorizing a given set of input data into classes based on one or more variables" (emphasis added), while [this source](https://machinelearningmastery.com/types-of-classification-in-machine-learning/) defines it both as a "task" and a "predictive modeling problem." As you are the domain expert, I trust your judgement here.
 
> I would normally agree but considering I was asked to define them during my presentation, I included them.

I don't remember that! 😲 I would double check with @smiths on this then. ¯\\\_(ツ)_/¯

**Comment by LesleyWheat** [comment]
Blog posts are not credible sources. This is literally the reason I included a definition in my document. [As common knowledge, it does not require a citation.](https://writing.wisc.edu/handbook/assignments/quotingsources/) If you checked my references, you would see that this definition makes sense.

> I don't remember that! 😲 I would double check with @smiths on this then. ¯\_(ツ)_/¯

If he disagrees with the definition, he can bring it up but it is valid for this area and [as common knowledge, does not require a citation.](https://writing.wisc.edu/handbook/assignments/quotingsources/).
