### ISSUE TITLE
SRS Review: General Definitions Section

### ISSUE THREAD

**Issue by samm82** [LesleyWheat/CAS741_CEWS#9]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

- [x] The introduction should be "This section collects **the** equations...."
- [ ] The discrete math of $E_{\text{RNG}}$ doesn't seem to be right. If it is a function, then it looks like you are defining it as a set, so [the appropriate notation](https://gitlab.cas.mcmaster.ca/smiths/se2aa4_cs2me3/-/blob/master/Lectures/L08_MathematicsForMIS/MathematicsForMIS.pdf) should be used.
- [ ] GD1 seems to calculate two things at once: $E_{\text{RNG}}$ and $V$. I think $E_{\text{RNG}}$ should be moved to be a separate GD or even a TM.
- [ ] In the description of $P$, should it be "dimension" since it only has one dimension $(m)$?
- [ ] Descriptions for many variables are not provided.

**Comment by LesleyWheat** [comment]
>The discrete math of  doesn't seem to be right. If it is a function, then it looks like you are defining it as a set, so [the appropriate notation (https://gitlab.cas.mcmaster.ca/smiths/se2aa4_cs2me3/-/blob/master/Lectures/L08_MathematicsForMIS/MathematicsForMIS.pdf) should be used.

$E_{RNG}$ is a function as a statement returning T/F hence the "lesser than equals" operator. It is not defined as a set based on https://gitlab.cas.mcmaster.ca/smiths/se2aa4_cs2me3/-/blob/master/Lectures/L08_MathematicsForMIS/MathematicsForMIS.pdf (just because it is uppercase does not mean it is a set).

> GD1 seems to calculate two things at once:  and . I think  should be moved to be a separate GD or even a TM.

$V$ is the output, $E_{RNG}$ is the calculation used for each element which could just be written in one line. GD1 is already exposing implementation that it shouldn't be exposing so I'm not further clarifying it or breaking it down.

> In the description of P, should it be "dimension" since it only has one dimension (m)?
$m$ can be greater than 1.

> Descriptions for many variables are not provided.

Math or written descriptions are provided for all variables.

**Comment by samm82** [comment]
> ERNG is a function... (just because it is uppercase does not mean it is a set).

By definition, a function is a set of ordered pairs. You can use function notation or set notation to define it, but wrapping it in square brackets is incorrect.

> > In the description of $P$, should it be "dimension" since it only has one dimension ($m$)?

> $m$ can be greater than 1.

Then if $m$ is the number of dimensions it should be " $m$ dimensions"; saying "dimensions $m$" makes it sounds like you are introducing its dimension to be $m$, which is only one value which confused me.

> Math or written descriptions are provided for all variables.

$p_i$ and $p_j$ have no descriptions (if they represent elements of the set $P$, they should have some explanation as to which elements they are, since sets are unordered).

**Comment by LesleyWheat** [comment]
> > ERNG is a function... (just because it is uppercase does not mean it is a set).
> 
> By definition, a function is a set of ordered pairs. You can use function notation or set notation to define it, but wrapping it in square brackets is incorrect.

No, you can mix square and round brackets in equations for readability, pretty common. In fact, the source I cite for my notation uses square brackets in some equations and round in others when the result in the bracket would be a number (not a set). 
![image](https://user-images.githubusercontent.com/29044132/219148435-e3041466-a8fc-47a6-a6f1-d7ca538cb50d.png)


> > > In the description of P, should it be "dimension" since it only has one dimension (m)?
> 
> > m can be greater than 1.
> 
> Then if m is the number of dimensions it should be " m dimensions"; saying "dimensions m" makes it sounds like you are introducing its dimension to be m, which is only one value which confused me.

Whether you think of it as $P$ has 1 dimension with size $n$ and then each point has a $m$ dimensions or $P$ has two dimensions ($n$ x $m$), doesn't matter. But the standard way of saying it is it is a set of points and then people usually understand that points can have multiple dimensions but I stated that explicitly.

The actual definition does not go into this much detail.
![image](https://user-images.githubusercontent.com/29044132/219156357-a116d3ad-969d-4b0a-a9ba-78fc96c0c2e7.png)


> 
> > Math or written descriptions are provided for all variables.
> 
> pi and pj have no descriptions (if they represent elements of the set P, they should have some explanation as to which elements they are, since sets are unordered).

$P$ is a set of $n$ points in real space with dimension(s) $m$ with elements $p_{i}$: $i=1,...,n$.
While sets are not ordered, their elements still have identifiers/indices (even if those identifiers are arbitrary). They don't need to be ordered.

**Comment by samm82** [comment]
I'm not sure if I'm articulating what I mean for these points well enough, and I don't think virtual correspondence is the best medium to do so. We can talk in person at some point if you want, or you can just ignore these discussion points/close the issue.
